baseurl = "/"
languageCode = "en-us"
title = "Zhuojie Zhou"
theme = "XMin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[params]
    description = "Zhuojie Zhou"
